/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package escuela;

import java.awt.Color;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author destr
 */
public class Entrar extends javax.swing.JFrame {
    int id =0;
    Usuario user;
    ArrayList<Usuario> users = new ArrayList<Usuario>();
    File file = new File("Usuarios.txt");
   
    /**
     * Creates new form Registrar
     */
    public Entrar() throws FileNotFoundException, IOException {
        initComponents();
        
        DataInputStream archivoRead;
        
        archivoRead = new DataInputStream(new FileInputStream(file));
        
        
        while(archivoRead.available() > 0){
            int readID = archivoRead.readInt();
            String readNombre = archivoRead.readUTF();
            String readPaterno = archivoRead.readUTF();
            String readMaterno = archivoRead.readUTF();
            String readNombreUsuario = archivoRead.readUTF();
            String readPassword = archivoRead.readUTF();
            String readPerfil = archivoRead.readUTF();
            String readSeparador = archivoRead.readUTF();
            
            Usuario temp = new Usuario();
            
            temp.setId(readID);
            temp.setNombre(readNombre);
            temp.setaPaterno(readPaterno);
            temp.setaMaterno(readMaterno);
            temp.setNombreUsuario(readNombreUsuario);
            temp.setPassword(readPassword);
            temp.setPerfil(readPerfil);
            
            users.add(temp);
        }

        
    }
    

    
    public Entrar(Usuario us) throws FileNotFoundException, IOException{
        initComponents();
        
        DataInputStream archivoRead;
        
        archivoRead = new DataInputStream(new FileInputStream(file));
        
        
        while(archivoRead.available() > 0){
            int readID = archivoRead.readInt();
            String readNombre = archivoRead.readUTF();
            String readPaterno = archivoRead.readUTF();
            String readMaterno = archivoRead.readUTF();
            String readNombreUsuario = archivoRead.readUTF();
            String readPassword = archivoRead.readUTF();
            String readPerfil = archivoRead.readUTF();
            String readSeparador = archivoRead.readUTF();
            
            Usuario temp = new Usuario();
            
            temp.setId(readID);
            temp.setNombre(readNombre);
            temp.setaPaterno(readPaterno);
            temp.setaMaterno(readMaterno);
            temp.setNombreUsuario(readNombreUsuario);
            temp.setPassword(readPassword);
            temp.setPerfil(readPerfil);
            
            users.add(temp);
        }
        
        us.setId(id);
        id+=1;
        users.add(us);
                
        file.delete();
        
        DataOutputStream archivoWrite;
        
        archivoWrite = new DataOutputStream(new FileOutputStream(file));
        
        for(int i=0; i<users.size(); i++){
            archivoWrite.writeInt(users.get(i).getId());
            archivoWrite.writeUTF(users.get(i).getNombre());
            archivoWrite.writeUTF(users.get(i).getaPaterno());
            archivoWrite.writeUTF(users.get(i).getaMaterno());
            archivoWrite.writeUTF(users.get(i).getNombreUsuario());
            archivoWrite.writeUTF(users.get(i).getPassword());
            archivoWrite.writeUTF(users.get(i).getPerfil());
            archivoWrite.writeUTF("#");
            
        }
        
        archivoWrite.close();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usuarioCampo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        contraseñaCampo = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnEntrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel1.setText("Nombre de Usuario");

        usuarioCampo.setForeground(new java.awt.Color(153, 153, 153));
        usuarioCampo.setText("Nombre de Usuario");
        usuarioCampo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usuarioCampoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usuarioCampoFocusLost(evt);
            }
        });
        usuarioCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioCampoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña");

        contraseñaCampo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contraseñaCampoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contraseñaCampoFocusLost(evt);
            }
        });
        contraseñaCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaCampoActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Mostrar Contraseña");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        jButton2.setText("Mostrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        jLabel3.setText("Login");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 94, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir)
                    .addComponent(jButton2)
                    .addComponent(jCheckBox1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addComponent(usuarioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnEntrar)
                            .addGap(18, 18, 18)
                            .addComponent(registrar))
                        .addComponent(contraseñaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuarioCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contraseñaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar)
                    .addComponent(registrar))
                .addGap(38, 38, 38)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioCampoActionPerformed

    private void usuarioCampoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioCampoFocusGained
        if(usuarioCampo.getText().equals("Nombre de Usuario")){
            usuarioCampo.setText("");
        }
        usuarioCampo.setForeground(Color.black);
    }//GEN-LAST:event_usuarioCampoFocusGained

    private void usuarioCampoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usuarioCampoFocusLost
        if(usuarioCampo.getText().equals("")){
            usuarioCampo.setText("Nombre de Usuario");
            usuarioCampo.setForeground(new Color(153,153,153));
        }
        else{
            usuarioCampo.setForeground(new Color(0,0,0));
        }
        
    }//GEN-LAST:event_usuarioCampoFocusLost

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            contraseñaCampo.setEchoChar((char)0);
        }
        else{
            contraseñaCampo.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void contraseñaCampoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraseñaCampoFocusGained
        
        
    }//GEN-LAST:event_contraseñaCampoFocusGained

    private void contraseñaCampoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contraseñaCampoFocusLost
        
    }//GEN-LAST:event_contraseñaCampoFocusLost

    private void contraseñaCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaCampoActionPerformed

    }//GEN-LAST:event_contraseñaCampoActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        for(int i =0; i<users.size(); i++){
            
            if(users.get(i).getNombreUsuario().equals(usuarioCampo.getText())){
                if(users.get(i).getPassword().equals(contraseñaCampo.getText())){
                    if(users.get(i).getPerfil().equals("Administrador")){
                        panelPrincipal n = new panelPrincipal(users.get(i).getPerfil());
                        n.setVisible(true);
                        dispose();
                        return;
                    }
                    if(users.get(i).getPerfil().equals("Coordinador")){
                        panelPrincipal n = new panelPrincipal(users.get(i).getPerfil());
                        n.setVisible(true);
                        dispose();
                        return;
                    }
                }
            }
        }
        
        JOptionPane.showMessageDialog(this, "El usuario / contraseña es incorrecto.");
        
        
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        for(int i =0; i<users.size(); i++){
            System.out.print(users.get(i).getNombreUsuario());
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        panelPrincipal n = new panelPrincipal("Registrar");
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_registrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Entrar().setVisible(true);
                } catch (IOException ex) {
                    //Logger.getLogger(Entrar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPasswordField contraseñaCampo;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registrar;
    private javax.swing.JTextField usuarioCampo;
    // End of variables declaration//GEN-END:variables
}
